### PR TITLE
Update serialosc and study files

### PR DESCRIPTION
**Pull request by 256k**
The current state of the grid studies for pure data are non functional out of the box. the examples depend on missing objects from external libraries no longer maintained. 

This PR updates the the `serialosc.pd` file with build in objects and updates the study files to reflect this update.

it also adds a local instance of the counter abstraction.

updated serialosc.pd:
image

I have no vivid recollection where did i get this fix or if i have put in the work myself to adjust it, could be either one tbh, I just would like to see the pd studies updated to a usable state aligned with the vanilla pd currently distributed.

example of updated study file with routing and counter:
image

### CODE REVIEW

**Comment by tehn** [comment]
thanks tons! @dndrks

**Comment by dndrks** [comment]
thanks so so much!!
i totally forgot this standalone repository existed — the Pd study was updated (along with sunsetting the serialosc abstraction) this year: https://monome.org/docs/grid/studies/pd/

just to confirm, do the approaches and files contained in that study not work now? there is an installation of two externals thru the Pd library, which seem to be currently maintained and supported. happy to do additional investigation, but i just wanted to confirm (+ apologies for any doubled-work!!)

**Comment by 256k** [comment]
oh well i guess i never paid attention to that. i just assumed that it was referencing the old pd-extended library. my bad 🙂 

to be fair i've had this fix for a while sitting on my computer (over a year now) but i felt like it was about time to make a PR for it having never noticed the studies update i guess

**Comment by dndrks** [comment]
oh, no no, MY bad for not doubling those changes here. i’ll take a look at the diffs and see if there isn’t a way to merge our work! :)

thanks so so much, again!

**Comment by 256k** [comment]
hey it's all good, happy to contribute in any small way 🙂

**Comment by 256k** [comment]
ahh, see i think i understand now. the readme file links to an old version of the pd studies which reference pd-extended. this was probably where i just assumed it was outdated.

**Comment by dndrks** [comment]
amazing, thank you so much!
i've put together a PR for the changes made in 2023 from @xdavevadx + myself, getting the trio of us on as co-authors :)
this has tested well on my + Dave's end -- Fayek, you wanna give [this](https://github.com/monome/grid-studies-pd/pull/3) a spin and do final sign-off?

**Comment by 256k** [comment]
sure will do

**Comment by dndrks** [comment]
thank you so so much!!!

**Pull request closed without merging**
